In [50]:
import torch as t
import numpy as np

## 0 注意事项
1 tensor类似python中的不可变变量，所以类似a.view(1,4)执行后，a本身是不会产生变化的。

2 部分tensor的方法可以执行tensor的改变，例如x.add_(y),即为x=x+y，但是普通的x.add(y)是无法改变x本身的。

## 1 tensor的初始化

1直接进行赋值。a=t.Tensor([1,2,4,5])

2a=t.rand(shape)

3a=t.zeros(shape)

4a=t.ones(shape)

## 2 tensor中的乘法
1tensor中*是对应元素相乘，或者其他的数组计算，总之不遵守矩阵乘法规则

2tensor中torch.mm()是专门用来矩阵乘法的。

3tensor中矩阵和数组是两个概念，也没有列向量的概念。tensor无法表示为列向量，只能表示为一个人4*1的矩阵.

例如，a=t.rand(4),b=t.rand(4,1),c=t.mm(a,b)，这时c是无法计算的，应为一维tensor无法和二维tensor做矩阵乘法，应该把a改为a=t.rand(1,4)。


## 3 tensor中的变形操作
1 t.reshape()，可以应用于任意维度。例如行向量转4*1矩阵

2 t.t(),只能应用于二维tensor的转置

3 torch.transpose(input, dim0, dim1)：交换两个维度。可以应用于任意维度的tensor。常用语图片的旋转。

4 t.squeeze(input)：去除那些维度大小为1的维度 

5 还有一个tensor自己的方法，用来改变自身大小，view



In [74]:
# squeeze的应用
a=t.tensor([1,2,4,4])
a=t.reshape(a,[4,1])
print(a)
a=t.squeeze(a)
print(a)

#view的应用
b=t.Tensor(1,4)
print(b)
b=b.view(-1,1)
print(b)





tensor([[1],
        [2],
        [4],
        [4]])
tensor([1, 2, 4, 4])
tensor([[-2.5569e-26,  4.5915e-41,  1.4612e+23,  7.6791e-43]])
tensor([[-2.5569e-26],
        [ 4.5915e-41],
        [ 1.4612e+23],
        [ 7.6791e-43]])


## 4 tensor中的组合操作
1 torch.cat(seq, dim=0, out=None)(concatenate,组合） 

In [86]:
x1 = t.rand(2, 5)
y1 = t.rand(3, 5)
z1 = t.cat([x1, y1])
z2=t.cat([x1,y1],0)
print(z2)
# z3=t.cat([x1,y1],1)，这个操作就不对了，因为如果按照dim=1组合的话，x1只有两行，不能组合到y1上去。
x2=t.rand(3,5)
z3=t.cat([x2,y1],1)
print(z3)


tensor([[0.3289, 0.7240, 0.1107, 0.7279, 0.4546],
        [0.7002, 0.4043, 0.9092, 0.5928, 0.5989],
        [0.6032, 0.0133, 0.2696, 0.7771, 0.2774],
        [0.9897, 0.9710, 0.6988, 0.8683, 0.9272],
        [0.6534, 0.5714, 0.9044, 0.9126, 0.2624]])
tensor([[0.7640, 0.0811, 0.0388, 0.0842, 0.4306, 0.6032, 0.0133, 0.2696, 0.7771,
         0.2774],
        [0.5613, 0.9848, 0.8707, 0.6648, 0.8495, 0.9897, 0.9710, 0.6988, 0.8683,
         0.9272],
        [0.2767, 0.3555, 0.1163, 0.1815, 0.2954, 0.6534, 0.5714, 0.9044, 0.9126,
         0.2624]])


## 5tensor中的数学操作
1 求取所有元素总和。tensor.sum()

2 求取所有元素平均值，tensor.mean()

In [112]:
a=t.ones(3,4)
print(a)
print(a.sum())
print(a.mean())


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor(12.)
tensor(1.)
torch.Size([])


In [67]:
# 1 size的使用
a=t.Tensor(4,1)
# print(t.size(a)),这种会报错，torch中没有size函数，size是tensor自己的方法。
print(a.size())
print(a.size()[0])


torch.Size([4, 1])
4


## 6 tensor的梯度计算



In [116]:
import torch.autograd as autograd
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim



In [138]:
# 1修改requires_grad属性
a=t.ones(2,3,requires_grad=True)
a=t.Tensor([1,3,4])
a.requires_grad=True
print(a.requires_grad)

# 2初始的tensor不能对自身进行运算，否则无法求梯度
x=t.ones(2,2,requires_grad=True)
x=x*2
y=x.sum()
y.backward()
print(x.grad)

#3 只能是标量对向量求梯度，无法求向量对向量的梯度
x=t.ones(2,2,requires_grad=True)
y=2*x
# y.backward()报错，无法求向量对向量的梯度

# 4只能求对初始tensor的梯度
x=t.ones(2,2,requires_grad=True)
y=2*x
z=y*y
out=z.sum()
print(out)
out.backward()
print('x.grad=',x.grad)
print('y.grad=',y.grad)
print('z.grad=',z.grad)

# 5可以使用雅克比向量积的方式通过链式求导法则计算向量对向量的倒数。







True
None
tensor(16., grad_fn=<SumBackward0>)
x.grad= tensor([[8., 8.],
        [8., 8.]])
y.grad= None
z.grad= None
